#start docker kernel + python
FROM python:3.11-slim-bullseye

#ENV (show logs)
ENV PYTHONUNBUFFERED=1 

#update kernal and install dependance
RUN apt-get update && apt-get install -y gcc libpq-dev

#create project folder on kernel
WORKDIR /app

#copy requirements
COPY db_requirements.txt /app/db_requirements.txt

#install requirements
RUN pip install --no-cache-dir -r db_requirements.txt

#copy code to docker
COPY . /app