# Generated by Django 5.0.6 on 2025-06-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_message_room_message_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
